# Generated by Django 5.1.1 on 2024-09-15 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('timing', models.DateTimeField()),
                ('area', models.CharField(max_length=200)),
                ('celebrity', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('music', 'Music'), ('sports', 'Sports'), ('conference', 'Conference'), ('workshop', 'Workshop')], max_length=50)),
                ('event_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_maker.eventmanager')),
            ],
        ),
    ]
