# Generated by Django 5.1.1 on 2024-09-16 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_maker', '0003_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
    ]
